version: "3"
services:
  bot:
    build: ./bot
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - ./bot/.env
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    restart: always
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017
    restart: always
