version: "3"
services:
  bot:
    build: .
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017
