version: "3"
services:
  bot:
    build: ./bot
    command: yarn dev
    volumes:
      - ./bot:/glitch_bot
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - ./bot/.env
    environment:
      NODE_ENV: development
      LOG_LEVEL: info
    ports:
      - 8081:8081
    restart: always
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: always
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ["ngrok", "http", "bot:8081"]
