name: CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[NO TESTS]') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install packages
        run: yarn --cwd ./bot install

      - name: Run mocha tests
        run: yarn --cwd ./bot test
  deploy: 
    runs-on: ubuntu-latest
    needs: run-tests 
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '[NO DEPLOY]') }}
    steps:
      - name: Deploy to docker-compose
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST  }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH  }}
            git pull -f
            docker-compose -f ${{ secrets.DC_FILE }} build
            docker-compose -f ${{ secrets.DC_FILE }} up -d


