name: CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install packages
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd ./bot install

      - name: Run mocha tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: --cwd ./bot test
  deploy: 
    runs-on: ubuntu-latest
    needs: run-tests 
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Deploy to docker-compose
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST  }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH  }}
            git pull -f
            docker-compose -f ${{ secrets.DC_FILE }} build
            docker-compose -f ${{ secrets.DC_FILE }} up -d


