name: CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup test environment
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Run mocha tests
        script: |
          cd bot
          npm run test

      - name: Deploy to docker-compose
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST  }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH  }}
            git pull -f
            docker-compose -f ${{ secrets.DC_FILE }} build
            docker-compose -f ${{ secrets.DC_FILE }} up -d

